from typing import Protocol

from customer360.contracts.public import AgentRequest, AgentResponse, QueryReceipt


class AgentTools(Protocol):
    def execute_sql(self, sql: str) -> QueryReceipt: ...
    def search_tables(self, query: str) -> tuple[dict, ...]: ...
    def search_columns(self, query: str) -> tuple[dict, ...]: ...
    def search_metrics(self, query: str) -> tuple[dict, ...]: ...
    def get_table_schema(self, table_name: str) -> tuple[dict, ...]: ...
    def get_metric_definition(self, metric_name: str) -> dict: ...
    def get_business_glossary(self, term: str) -> tuple[dict, ...]: ...
    def get_join_paths(self, query: str) -> tuple[dict, ...]: ...


class Agent(Protocol):
    def respond(self, request: AgentRequest, tools: AgentTools) -> AgentResponse: ...
